# Services
services:
    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./conf:/etc/nginx/conf.d
            - ./www:/var/www/html
            - ./logs:/var/log/nginx:rw
        ports:
            - "127.0.0.1:80:80"
        networks:
            default:
                aliases:
                    - kingboost.local

    # PHP 7.4 fpm Service (with ioncube)
    php74:
        container_name: php74
        build:
            context: ./images/php74
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ~/.composer:/var/www/.composer
            - ~/.ssh:/var/www/.ssh
            - ~/.ssh/id_ed25519.pub:/var/www/.ssh/authorized_keys
            - ./www:/var/www/html

    # MariaDB Service
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        volumes:
            - db-data:/var/lib/mysql
            - ./init/db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: kingboost_dev
            MYSQL_USER: kingboost
            MYSQL_PASSWORD: kingboost

    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        ports:
            - "2308:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOSTS: mariadb
            PMA_USER: kingboost
            PMA_PASSWORD: kingboost
            UPLOAD_LIMIT: 512M
            MEMORY_LIMIT: 512M
        depends_on:
            - mariadb

    # Redis engine
    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        ports:
            - "127.0.0.1:6379:6379"

volumes:
    db-data: